# Generated by Django 3.2.3 on 2021-05-30 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
